# Generated by Django 5.0.6 on 2024-09-15 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0002_rename_imagen_empleado_imagen_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='empresa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('ContadorL', 'ContadorL'), ('Auxiliar Contable', 'Auxiliar Contable'), ('RRHHL', 'RRHHL'), ('RRHH', 'RRHH'), ('Empleado General', 'Empleado General')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado'),
        ),
    ]
