# Generated by Django 5.0.6 on 2024-09-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0003_liquidacion_empresa_alter_usuarios_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorcentajesLegales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salud_empleado', models.DecimalField(decimal_places=2, help_text='Porcentaje de salud a cargo del empleado ejemplo: 4 % ingrese 0.04', max_digits=5)),
                ('salud_empresa', models.DecimalField(decimal_places=2, help_text='Porcentaje de salud a cargo de la empresa', max_digits=5)),
                ('pension_empleado', models.DecimalField(decimal_places=2, help_text='Porcentaje de pensión a cargo del empleado', max_digits=5)),
                ('pension_empresa', models.DecimalField(decimal_places=2, help_text='Porcentaje de pensión a cargo de la empresa', max_digits=5)),
                ('vacaciones', models.DecimalField(decimal_places=2, help_text='Porcentaje de vacaciones', max_digits=5)),
                ('cesantias', models.DecimalField(decimal_places=2, help_text='Porcentaje de cesantías', max_digits=5)),
                ('intereses_cesantias', models.DecimalField(decimal_places=2, help_text='Porcentaje de intereses sobre cesantías', max_digits=5)),
                ('icbf', models.DecimalField(decimal_places=2, help_text='Porcentaje de contribución al ICBF', max_digits=5)),
                ('sena', models.DecimalField(decimal_places=2, help_text='Porcentaje de contribución al SENA', max_digits=5)),
                ('caja_compensacion', models.DecimalField(decimal_places=2, help_text='Porcentaje de contribución a la caja de compensación', max_digits=5)),
                ('riesgo_laboral1', models.DecimalField(decimal_places=2, help_text='Porcentaje de riesgo laboral - Clase 1', max_digits=5)),
                ('riesgo_laboral2', models.DecimalField(decimal_places=2, help_text='Porcentaje de riesgo laboral - Clase 2', max_digits=5)),
                ('riesgo_laboral3', models.DecimalField(decimal_places=2, help_text='Porcentaje de riesgo laboral - Clase 3', max_digits=5)),
                ('riesgo_laboral4', models.DecimalField(decimal_places=2, help_text='Porcentaje de riesgo laboral - Clase 4', max_digits=5)),
                ('riesgo_laboral5', models.DecimalField(decimal_places=2, help_text='Porcentaje de riesgo laboral - Clase 5', max_digits=5)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, help_text='Monto del auxilio de transporte', max_digits=5)),
                ('fecha_vigencia', models.DateField(help_text='Fecha de inicio de vigencia de estos porcentajes')),
            ],
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='codigo_departamento',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='codigo_ciudad',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='nit',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
