# Generated by Django 5.0.6 on 2024-09-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0004_porcentajeslegales_remove_ciudad_codigo_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porcentajeslegales',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
